[package]
name = "shared-wasm-experiments"
version = "0.1.0"
authors = ["Jari Pennanen <ciantic@oksidi.com>"]
edition = "2018"
publish = false
repository = ""

[lib]
crate-type = ["cdylib", "rlib"]

[features]
default = ["console_error_panic_hook"]

[dependencies]
wasm-bindgen = "0.2.63"
wasm-bindgen-futures = "*"
futures-channel-preview = "0.3.0-alpha.18"
console_error_panic_hook = { version = "0.1.6", optional = true }
wee_alloc = { version = "0.4.5", optional = true }
once_cell = "*"
crossbeam-channel = "*"
js-sys = "*"
rayon = "*"

[dependencies.web-sys]
version = "*"
features = [
  'CanvasRenderingContext2d',
  'ErrorEvent',
  'Event',
  'ImageData',
  'Navigator',
  'Window',
  'Worker',
  'Blob',
  'BlobPropertyBag',
  'Url',
  'WorkerOptions',
  'DedicatedWorkerGlobalScope',
  'MessageEvent',
]
[dev-dependencies]
wasm-bindgen-test = "0.3.13"

[profile.release]
opt-level = "s" # Tell `rustc` to optimize for small code size.

